name: OWASP ZAP Scan

on:
  push:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed for reports

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan (No Docker)
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: "http://testphp.vulnweb.com/"

